kind: pipeline
name: kernel_santoni

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Compile
    image: ubuntu:rolling
    commands:
      - apt-get -y update
      - apt-get -y install bc build-essential bison bash python2 flex elfutils libelf-dev libisl-dev zip unzip curl git wget zstd
      - apt-get -y install gzip gettext fdclone pv texinfo libelf-dev libgomp1 make tar libgmp-dev libmpfr-dev libmpc-dev libisl-dev build-essential git curl bash bc bison flex
      - curl -LSsO https://github.com/nathanchance/scripts/raw/master/env/stubs/bldgcc
      - source bldgcc
      - bldgcc arm64
      - ls ~/gcc/10.1.0
#
# Open the bldgcc file -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync       when:
      branch:
        - master
